@url=http://localhost:3000
###
GET {{url}}/recipes/category
###
DELETE  {{url}}/recipes/1
###
PUT  {{url}}/recipes/1

###
POST  {{url}}/users
content-type: application/json

{
    "name": ""
}
###
PUT  {{url}}/users/2
content-type: application/json

{
    "name": ""
}

###
DELETE {{url}}/users/5
###
POST  {{url}}/recipes
content-type: application/json

{
    "title":"telur gulung",
    "ingredients": "telur",
    "photo": "http://localhost",
    "users_id":4
}

###

GET http://localhost:3000/users

###
POST  {{url}}/auth/register
content-type: application/json

{
    "email":"ean@ean.",
    "name":"ean",
    "password":"123"
}

###
POST  {{url}}/auth/login
content-type: application/json

{
    "email":"ean@ean.s",
    "password":"123"
}

###
GET  {{url}}/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5MjE4NzlhLWQ5MWEtNGQ5My04OWRhLTRmZmY4ZGU1ODYwNyIsImVtYWlsIjoiZWFuQGVhbi5teSIsImZ1bGxuYW1lIjoiZWFuIiwicGhvdG8iOm51bGwsInZlcmlmIjowLCJvdHAiOm51bGwsImNyZWF0ZWRfYXQiOm51bGwsImlhdCI6MTY3NzA0OTI0MSwiZXhwIjoxNjc4MzYzMjQxfQ.VNUjrVxZ4lXPL4WKOuyjDWDTffZnvJWr1LKE7UlXdR4

###
GET  {{url}}/recipes/my-recipe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkZDNhYzBhLWNjY2EtNDg2ZS05YWE5LTRiZDUxZjIyMGFhYiIsImVtYWlsIjoiZWFuQGVhbi5zZyIsImZ1bGxuYW1lIjoiZWFuIiwicGhvdG8iOm51bGwsInZlcmlmIjowLCJvdHAiOm51bGwsImNyZWF0ZWRfYXQiOm51bGwsImlhdCI6MTY3NzA1MDQ5MCwiZXhwIjoxNjc4MzY0NDkwfQ.rx8cJMr5j4SffAxdfoWKFXiD5s1qyQHXA_fGQAgrftE

###
POST  {{url}}/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMWJjZGY3LTI2OTYtNDZkZS1iYWI1LTI0ODBjNDFmN2U4OCIsImVtYWlsIjoiZnZ0MTg0MDFAbmV6aWQuY29tIiwiZnVsbG5hbWUiOiJuZXppZCIsInBob3RvIjpudWxsLCJ2ZXJpZiI6MSwib3RwIjoiNDQ0OTE5IiwiY3JlYXRlZF9hdCI6bnVsbCwiaWF0IjoxNjc3MjI2NDYwLCJleHAiOjE2Nzg1NDA0NjB9.bld1-dLppchtmv5Hgbp8hVh-yEuEcNJ8sAGw-Qtf-w0
content-type: application/json

{
    "title":"telur rebus",
    "ingredients": "telur",
    "photo": "http://localhost"
}

###